name: Frontend deployment.
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  pull_request_review:
    types:
      - submitted

jobs:
  build:
    name: Build Static Website
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build Vite Project
      run: |
        cd frontend
        npm install
        npm run build
    
    - name: Deploy static website to S3 bucket
      run: |
        cd frontend 
        aws s3 sync dist s3://${{ secrets.BLOG_BUCKET }} --delete
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.BLOG_DISTRIBUTION }} \
          --paths "/*"