name: IAC deployment.
on:
  push:
    branches:
      - master
    paths:
      - 'iac/**'
  pull_request_review:
    types:
      - submitted

env:
  IAC_STACK: IacStack

jobs:
  build:
    name: Build Infra Stack
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build Vite Project
      run: |
        cd frontend
        npm install
        npm run build
    
    - name: Create Iac Stack with CDK
      run: |
        cd iac
        npm install
        npm ci
        npm install -g aws-cdk
        cdk deploy $IAC_STACK --require-approval never